{% set name = "pandas-ta" %}
{% set version = "0.4.26b" %}
{% set python_min = "3.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.pandas-ta.dev/assets/zip/pandas_ta-0.4.26b0.tar.gz
  sha256: 0fd16f73359020499dc601f3954ef77ca1a06cb8eba6354fafc398e324fa2c87

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numba >=0.60.0
    - numpy >=2.1.0
    - pandas >=2.2.3
    - python >={{ python_min }}
    - setuptools >=75.7.0
    - tqdm >=4.67.1

test:
  imports:
    - pandas_ta
    - pandas_ta.candle
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.pandas-ta.dev
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Technical Analysis Indicators - Pandas TA is an easy to use Python 3 Pandas Extension with 130+ Indicators'
  description: |
    Pandas Technical Analysis (Pandas TA) is an easy to use library that
    leverages the Pandas package with more than 130 Indicators and 
    Utility functions and more than 60 TA Lib Candlestick Patterns. Many
    commonly used indicators are included, such as Candle Pattern
    (cdl_pattern), Simple Moving Average (sma) Moving Average Convergence
    Divergence (macd), Hull Exponential Moving Average (hma), Bollinger
    Bands (bbands), On-Balance Volume (obv), Aroon & Aroon Oscillator
    (aroon), Squeeze (squeeze) and many more.
  doc_url: https://www.pandas-ta.dev/api/
  dev_url: https://www.pandas-ta.dev/support/bugs-and-features/

extra:
  recipe-maintainers:
    - jan-janssen
